### ISSUE TITLE
Html tags support

### ISSUE THREAD

**Issue by john454** [jbr/jQuery.highlightRegex#18]
`<script type="text/javascript">$(document).highlightRegex(/<p>((.|\r|\n)*?)\<\/p>/ig);</script>`

//this not working!
`<p>text <b>bold text</b> hello</p>`

Thank you for quick fix

**Comment by jbr** [comment]
Sorry, that's not the use case that this plugin was originally written to solve, and would take a substantial rewrite to make possible. Specifically, the use case requested would require scanning and replacing innerHTML, which could lead to odd DOM situations. I would recommend directly doing a regex string replacement on the innerHTML of your container. Hope that's a sufficient quick fix!

**Comment by jbr** [comment]
Actually, on further thought: It's not apparent to me what your desired result is, but potentially you could either `$('p').highlightRegex(/some regex/)`, or you could just `$('p').filter(function() {return $(this).html().match(/some regex/)})`

**Comment by jbr** [comment]
```js
$('p').each(function() { $(this).html($(this).html().replace(/some regex/g)) })
```
